spring:
  application:
    name: appointments
  datasource:
    url: jdbc:postgresql://localhost:5432/appointmentsdb
    username: test_appointments
    password: password
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: verify
#    database: postgresql
#    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
    com.alntech.appointments.controllers.ExpertController: DEBUG