spring:
  application:
    name: appointments
  datasource:
    url: jdbc:postgresql://localhost:5432/appointmentsdb
    username: test_appointments
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
